---
driver:
  name: vagrant

provisioner:
  name: ansible
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.8
  - name: debian-8
  - name: debian-9
  # - name: amazon linux... TODO

suites:
- name: default
  provisioner:
    name: ansible_playbook
    playbook: 'test/integration/default/test.yml'
    additional_copy_path:
      - "."
